[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://backend-l4tfs5l2o-yogeshs-projects-6544e7db.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://backend-wheat-omega.vercel.app/api/:splat"
  status = 200
  force = true 